### ISSUE TITLE
Change blog post date

### ISSUE THREAD

**Issue by sanket1729** [rust-bitcoin/rust-bitcoin.github.io#2]
![Screenshot from 2023-03-21 19-01-49](https://user-images.githubusercontent.com/6881849/226782712-5befd2f6-f1a7-4e89-b6c2-f1fdb4dbd154.png)

Shows Feb 21st

**Comment by tcharding** [comment]
Isn't it the 21st in the US right now? Its the 22nd in Australia but I tailored this for @apoelstra

**Comment by tcharding** [comment]
Oh wrong month - woops

**Comment by tcharding** [comment]
Fixed by https://github.com/rust-bitcoin/www.rust-bitcoin.org/pull/4

**Comment by tcharding** [comment]
Thanks for raising the issue @sanket1729, FYI this repo only has build artifacts built from the source over at https://github.com/rust-bitcoin/www.rust-bitcoin.org/
