### ISSUE TITLE
github actions bot does not have correct permissions - I think

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin.github.io#6]
After merging into master just now the github pages deployment job fails

 https://github.com/rust-bitcoin/rust-bitcoin.github.io/actions/runs/6660388344/job/18101405770

I think the issue is that the bot hasn't got perms to commit to the `gh-pages` branch.

**Comment by tcharding** [comment]
cc @apoelstra

**Comment by apoelstra** [comment]
I just checked a "Allow GH Actions to create and approve pull request" box. Did that help?

**Comment by tcharding** [comment]
Looks like we are winning now that #5 merged! Way to go @realeinherjar.
