### ISSUE TITLE
fix: Cookbook for `rust-bitcoin@0.31` 

### ISSUE THREAD

**Issue by realeinherjar** [rust-bitcoin/rust-bitcoin.github.io#7]
TODOs for the `0.31.0` release:

- [ ] Instead of `cargo add bitcoin --features "std, rand-std"` just do `cargo add bitcoin --features "rand-std"` source: https://github.com/rust-bitcoin/rust-bitcoin/pull/2102#event-10563056915
- [ ] Segwit signing API changes with the new `Witness::p2wpkh` constructor source: https://github.com/rust-bitcoin/rust-bitcoin/pull/2084 Example in https://github.com/rust-bitcoin/rust-bitcoin/pull/2095
- [ ] Taproot signing API changes with the new `Witness::p2tr_key_spend` function source: https://github.com/rust-bitcoin/rust-bitcoin/pull/2097 Example in https://github.com/rust-bitcoin/rust-bitcoin/pull/2095

This is still a WIP list.

**Comment by tcharding** [comment]
All done in #14 except the first one and since its still technically correct I'm not going to go back and fix it.
